name: Build FastAPI Images

on: workflow_dispatch

permissions:
  contents: read

jobs:
  build-fastapi-images:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Docker Login
        uses: docker/login-action@v2.1.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Discover and Build Images
        run: |
          cd fastapi
          for dir in */; do
            # Extract version from the directory name
            version=${dir%/}

            echo "Building and pushing image for FastAPI $version"

            # Build and push the Docker image for this version
            docker buildx build \
              --platform linux/amd64,linux/arm64 \
              --push \
              --tag ${{ vars.DOCKERHUB_NAMESPACE }}/fastapi:$version \
              --file "$dir/Dockerfile" \
              "$dir"
          done
